---
- name: Uninstall development packages necessary for building Python
  homebrew:
    name: [pyenv, pyenv-virtualenv]
    state: absent
  ignore_errors: yes

- name: Install development packages necessary for building Python
  homebrew:
    name: [pyenv, pyenv-virtualenv]
    state: latest
  ignore_errors: yes

- name: Insert/Update "Pyenv" configuration block in ~/.bash_profile and ~/.zshrc
  blockinfile:
    create: yes
    path: "{{ item }}"
    block: |
      export PATH=$HOME/.pyenv/shims:$PATH
      eval "$(pyenv init -)"
    marker: "# Pyenv configuration"
  with_items:
    - ~/.zshrc
    - ~/.bash_profile

- name: Install PyEnv-update plugin
  git:
    repo: https://github.com/pyenv/pyenv-update.git
    dest: ~/.pyenv/plugins/pyenv-update
    update: yes
    force: yes

- name: Update Pyenv interpreter list
  shell: . ~/.bash_profile && pyenv update

- name: Uninstall existing Python interpreters
  shell: ". ~/.bash_profile && pyenv uninstall -f {{ item }}"
  loop: "{{ python }}"

- name: Install Python interpreters "{{ pyenv_python_versions }}"
  shell: ". ~/.bash_profile && pyenv install {{ item }}"
  loop: "{{ python }}"

- name: Set pyenv global
  shell: . ~/.bash_profile && pyenv global {{ pyenv_global }} && pyenv rehash
