version: "2"

services:

  server:
    build: ./server
#    image: galrabin/tidy
    ports:
      - 8000:8000
    volumes:
      - $HOME/.aws:/home/app/.aws/
    network_mode: "host"
    restart: unless-stopped

  openvpn-as:
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - INTERFACE=eth0 #optional
    volumes:
      - /tmp/config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194
      - 8000:8000
    network_mode: "host"
    restart: unless-stopped
