apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex1-q2
  labels:
    app: ex1-q2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ex1-q2
  template:
    metadata:
      labels:
        app: ex1-q2
    spec:
      containers:
      - name: ex1-q2
        image: galrabin/ex1_q2
        ports:
        - containerPort: 80