apiVersion: v1
kind: Service
metadata:
  name: tidy-service
spec:
  type: LoadBalancer
  selector:
    app: tidy
  ports:
  - name: "943"
    port: 943
    targetPort: 943
  - name: "9443"
    port: 9443
    targetPort: 9443
  - name: "1194"
    port: 1194
    targetPort: 1194
  - name: "8000"
    port: 8000
    targetPort: 8000